### ISSUE TITLE
Using external grafana and prometheus

### ISSUE THREAD

**Issue by acar-ctpe** [Azure/azure-managed-grafana#10]
Hello,

I accept this is for Managed Grafana, however is it possible to integrate with external prometheus or/and grafana solution?

Regards

**Comment by brahmnes** [comment]
Yes, it's possible to use Azure Managed Grafana with a prometheus instance you host yourself or from somewhere that's not Azure.

**Comment by shaunaa126** [comment]
@brahmnes is it possible to send data to an external grafana instead of the azure managed grafana? I am trying to send data to local grafana or grafana cloud but not sure what we need to do to hook up the data source.
