### ISSUE TITLE
any way to get more logs on what might be generating this error?

### ISSUE THREAD

**Issue by ansmah** [Azure/azure-managed-grafana#11]
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object, when trying to launch the 1.0. Also is there a repo where we can see what Azure objects you are creating?

**Comment by weng5e** [comment]
@ansmah are you refering to the azure money monitor? If so, you can add `--verbose` option to turn on verbose log. The command will be like `docker run azmoney.azurecr.io/azure-money-monitor:1.0 -s <subscription Id> --use-device-code --verbose`

The issue might be that you did not finish the Azure login process. The log will ask you to open a browser to login.

```
[18:18:54 INF] ***************************************************************************************
[18:18:54 INF] Login into Azure using Device Code.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.
```

**Comment by brahmnes** [comment]
Hi @ansmah , I am closing this since it's been two months old. Feel free to let us know if you are still encountering the problem.
