### ISSUE TITLE
Azure managed grafana can support Azure Devops plugin? 

### ISSUE THREAD

**Issue by AshishDadhich4h2** [Azure/azure-managed-grafana#7]
We came across the article https://grafana.com/grafana/plugins/grafana-azuredevops-datasource/
Is any feature request or on-going work for supporting Azure Devops plugin with **Azure managed grafana**

**Comment by brahmnes** [comment]
This is already supported in Azure Managed Grafana. An enterprise license, which you can purchase from Azure Portal, is needed for this to work though.

**Comment by AshishDadhich4h2** [comment]
@brahmnes Thank you !
